from enum import StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    CUSTOMER = "CUSTOMER"
    SUPPLIER = "SUPPLIER"


class CompanyType(StrEnum):
    CUSTOMER = "CUSTOMER"
    SUPPLIER = "SUPPLIER"
    LOGISTICS_PARTNER = "LOGISTICS_PARTNER"
    INSPECTION_PARTNER = "INSPECTION_PARTNER"
    PLATFORM_OPERATOR = "PLATFORM_OPERATOR"
    OTHER = "OTHER"


class CompanyVerificationStatus(StrEnum):
    NEW = "NEW"
    PROFILE_INCOMPLETE = "PROFILE_INCOMPLETE"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    SUSPENDED = "SUSPENDED"
    BLACKLISTED = "BLACKLISTED"


class RFQStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    AI_REVIEWED = "AI_REVIEWED"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    UNDER_OPERATOR_REVIEW = "UNDER_OPERATOR_REVIEW"
    APPROVED_FOR_TENDER = "APPROVED_FOR_TENDER"
    PUBLISHED = "PUBLISHED"
    QUOTING = "QUOTING"
    QUOTES_RECEIVED = "QUOTES_RECEIVED"
    CUSTOMER_REVIEW = "CUSTOMER_REVIEW"
    SUPPLIER_SELECTED = "SUPPLIER_SELECTED"
    ORDER_CREATED = "ORDER_CREATED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class RFQType(StrEnum):
    BY_DRAWING = "BY_DRAWING"
    BY_3D_MODEL = "BY_3D_MODEL"
    BY_PHOTO = "BY_PHOTO"
    BY_SAMPLE = "BY_SAMPLE"
    TENDER_RFQ = "TENDER_RFQ"
    REGULAR_SUPPLY = "REGULAR_SUPPLY"
    IMPORTED_PART_ALTERNATIVE = "IMPORTED_PART_ALTERNATIVE"
    OTHER = "OTHER"


class ManufacturingProcess(StrEnum):
    CNC_MACHINING = "CNC_MACHINING"
    METAL_CASTING = "METAL_CASTING"
    DIE_CASTING = "DIE_CASTING"
    INVESTMENT_CASTING = "INVESTMENT_CASTING"
    SAND_CASTING = "SAND_CASTING"
    PLASTIC_INJECTION_MOLDING = "PLASTIC_INJECTION_MOLDING"
    METAL_STAMPING = "METAL_STAMPING"
    FORGING = "FORGING"
    RUBBER_MOLDING = "RUBBER_MOLDING"
    SILICONE_MOLDING = "SILICONE_MOLDING"
    PU_CASTING = "PU_CASTING"
    SHEET_METAL = "SHEET_METAL"
    WELDING_FABRICATION = "WELDING_FABRICATION"
    TOOLING_MOLD_MAKING = "TOOLING_MOLD_MAKING"
    ASSEMBLY = "ASSEMBLY"
    SURFACE_TREATMENT = "SURFACE_TREATMENT"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class MaterialType(StrEnum):
    CARBON_STEEL = "CARBON_STEEL"
    STAINLESS_STEEL = "STAINLESS_STEEL"
    CAST_IRON = "CAST_IRON"
    ALUMINUM = "ALUMINUM"
    BRASS = "BRASS"
    COPPER = "COPPER"
    ZINC_ALLOY = "ZINC_ALLOY"
    ABS = "ABS"
    PP = "PP"
    PE = "PE"
    PA = "PA"
    POM = "POM"
    PC = "PC"
    PVC = "PVC"
    RUBBER = "RUBBER"
    SILICONE = "SILICONE"
    POLYURETHANE = "POLYURETHANE"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class QuoteStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    CLARIFICATION_NEEDED = "CLARIFICATION_NEEDED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    WITHDRAWN = "WITHDRAWN"


class OrderStatus(StrEnum):
    CREATED = "CREATED"
    TERMS_APPROVAL = "TERMS_APPROVAL"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    SAMPLE_PRODUCTION = "SAMPLE_PRODUCTION"
    SAMPLE_REVIEW = "SAMPLE_REVIEW"
    MASS_PRODUCTION = "MASS_PRODUCTION"
    INSPECTION = "INSPECTION"
    READY_TO_SHIP = "READY_TO_SHIP"
    IN_TRANSIT = "IN_TRANSIT"
    DELIVERED = "DELIVERED"
    CLOSED = "CLOSED"
    DISPUTE = "DISPUTE"
    CANCELLED = "CANCELLED"
