from enum import StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    CUSTOMER = "CUSTOMER"
    SUPPLIER = "SUPPLIER"


class CompanyType(StrEnum):
    CUSTOMER = "CUSTOMER"
    SUPPLIER = "SUPPLIER"
    LOGISTICS_PARTNER = "LOGISTICS_PARTNER"
    INSPECTION_PARTNER = "INSPECTION_PARTNER"
    PLATFORM_OPERATOR = "PLATFORM_OPERATOR"
    OTHER = "OTHER"
